package p2pfilesharing.client.GUI;

import java.io.File;
import java.io.IOException;
import java.util.Vector;

import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import p2pfilesharing.client.BLL.serverConnection;

public class AppForm extends javax.swing.JFrame {
	DefaultTableModel model;
    public AppForm(String username, int port) {
        initComponents();
        label_username.setText(username);
        label_port.setText("You are online on port " + port);
    	model = (DefaultTableModel) table_file.getModel();
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JScrollPane();
        table_file = new javax.swing.JTable();
        Sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();
        btn_upload = new javax.swing.JButton();
        btn_download = new javax.swing.JButton();
        btn_history = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        label_port = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("P2P File Sharing System");
        setBackground(new java.awt.Color(51, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        table_file.setBackground(new java.awt.Color(243, 213, 213));
        table_file.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Size"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_file.getTableHeader().setResizingAllowed(false);
        table_file.getTableHeader().setReorderingAllowed(false);
        Content.setViewportView(table_file);
        if (table_file.getColumnModel().getColumnCount() > 0) {
            table_file.getColumnModel().getColumn(0).setResizable(false);
            table_file.getColumnModel().getColumn(0).setPreferredWidth(100);
            table_file.getColumnModel().getColumn(1).setResizable(false);
            table_file.getColumnModel().getColumn(1).setPreferredWidth(500);
            table_file.getColumnModel().getColumn(2).setResizable(false);
            table_file.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        Sidebar.setBackground(new java.awt.Color(67, 108, 154));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 239, 208));
        jLabel1.setText("P2P File Sharing System");

        btn_refresh.setBackground(new java.awt.Color(189, 239, 208));
        btn_refresh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_upload.setBackground(new java.awt.Color(189, 239, 208));
        btn_upload.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_upload.setText("Upload");
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });

        btn_download.setBackground(new java.awt.Color(189, 239, 208));
        btn_download.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_download.setText("Download");
        btn_download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_downloadActionPerformed(evt);
            }
        });

        btn_history.setBackground(new java.awt.Color(189, 239, 208));
        btn_history.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_history.setText("History");
        btn_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_history, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_download, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(btn_refresh)
                .addGap(38, 38, 38)
                .addComponent(btn_upload)
                .addGap(39, 39, 39)
                .addComponent(btn_download)
                .addGap(41, 41, 41)
                .addComponent(btn_history)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(127, 229, 231));
        header.setToolTipText("");
        header.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        label_port.setBackground(new java.awt.Color(242, 242, 213));
        label_port.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        label_port.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_port.setText("You are online on port: ?");

        label_username.setBackground(new java.awt.Color(252, 245, 239));
        label_username.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        label_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_username.setText("user:?");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(label_port, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_username, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_port, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        
        chooser.setDialogTitle("Choose the files you want to upload");
        int result = chooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION)
        {
        	File[] selectedfiles = chooser.getSelectedFiles();
        	Vector<String> files = new Vector<>();
            for(File f : selectedfiles ) {
            	String path = f.getAbsolutePath();
                long size = f.length();
                String filename = f.getName();
                String file = filename + ";"+ size +";"+ path;
                files.add(file);
            }
            try {
                serverConnection.getInstance().sendUploadRequest(files);
            } catch (IOException e) {
                System.out.println("Lỗi:" + e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_uploadActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        try {
            serverConnection.getInstance().sendRefreshRequest();
        } catch (IOException e) {
            System.out.println("Lỗi:" + e.getMessage());
        }
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_downloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_downloadActionPerformed
        int selectedIndex = table_file.getSelectedRow();
        //Nếu có hàng được chọn mới thực hiện
        if(selectedIndex != -1)
        {
            int fileId = Integer.parseInt(table_file.getValueAt(selectedIndex, 0).toString());
            try {
                serverConnection.getInstance().sendDownloadRequest(fileId);
            } catch (IOException e) {
                System.out.println("Lỗi:" + e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_downloadActionPerformed

    private void btn_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historyActionPerformed
        
        try {
                serverConnection.getInstance().sendGetHistory();
        } catch (IOException e) {
            System.out.println("Lỗi:" + e.getMessage());
        }
    }//GEN-LAST:event_btn_historyActionPerformed
    



    
    public void addFileToTable(String id, String name, String size) {
        SwingUtilities.invokeLater(() -> {
        	model.addRow(new Object[]{id, name, size});
        });
        
    }
    public void clearTableFile()
    {
    	model.setRowCount(0);
    }              
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppForm(null,0).setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Content;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JButton btn_download;
    private javax.swing.JButton btn_history;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_upload;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_port;
    private javax.swing.JLabel label_username;
    private javax.swing.JTable table_file;
    // End of variables declaration//GEN-END:variables

}
